/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-3-31: 17h:23m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/hwwu/GitHub/ats-session-playground/zmq.sats: 3(line=3, offs=1) -- 61(line=8, offs=3)
*/

#ifndef __ZMQ
#define __ZMQ
#include <zmq.h>
#endif
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/string.sats: 1380(line=35, offs=1) -- 1419(line=37, offs=3)
*/

#include "libc/CATS/string.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/DATS/string.dats: 1566(line=41, offs=1) -- 1597(line=41, offs=32)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/string.sats: 1380(line=35, offs=1) -- 1419(line=37, offs=3)
*/

#include "libc/CATS/string.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_type(atstype_ptrk) atslab__ctx ;
atstkind_type(atstype_ptrk) atslab__sock ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(zmq_close)
ATSdyncst_mac(zmq_ctx_term)
ATSdyncst_mac(zmq_ctx_new)
ATSdyncst_mac(zmq_socket)
ATSdyncst_mac(zmq_bind)
ATSdyncst_mac(zmq_connect)
ATSdyncst_mac(atspre_g0uint_add_size)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(zmq_msg_init_size)
ATSdyncst_mac(atslib_strcpy_unsafe)
ATSdyncst_mac(zmq_msg_data)
ATSdyncst_mac(zmq_msg_send)
ATSdyncst_mac(zmq_msg_close)
ATSdyncst_mac(zmq_msg_init)
ATSdyncst_mac(zmq_msg_recv)
ATSdyncst_mac(atspre_malloc_gc)
ATSdyncst_mac(atspre_string_memcpy)
ATSdyncst_mac(atspre_strlen)
ATSdyncst_mac(atspre_g1uint_succ_size)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
/home/hwwu/GitHub/ats-session-playground/session.dats: 285(line=10, offs=1) -- 317(line=10, offs=33)
*/
ATSassume(_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__session) ;
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__close(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__create_server(atstype_funptr, atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__create_client(atstype_funptr, atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__send(atsrefarg0_type(atstype_boxed), atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__receive(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_copy__6(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_copy__6__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_copy__8(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_copy__8__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__10(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__10__1(atstkind_type(atstype_ptrk)) ;

/*
/home/hwwu/GitHub/ats-session-playground/session.dats: 336(line=13, offs=17) -- 467(line=18, offs=2)
*/
/*
local: 
global: close$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__close(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
// ATStmpdec_void(tmp1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 330(line=13, offs=11) -- 467(line=18, offs=2)
*/
ATSINSflab(__patsflab_close):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 348(line=13, offs=29) -- 467(line=18, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 369(line=14, offs=11) -- 392(line=14, offs=34)
*/
ATSINSmove_void(tmp1, zmq_close(ATSSELboxrec(arg0, postiats_tyrec_0, atslab__sock))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 404(line=15, offs=11) -- 429(line=15, offs=36)
*/
ATSINSmove_void(tmpret0, zmq_ctx_term(ATSSELboxrec(arg0, postiats_tyrec_0, atslab__ctx))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 348(line=13, offs=29) -- 467(line=18, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__close] */

/*
/home/hwwu/GitHub/ats-session-playground/session.dats: 498(line=21, offs=29) -- 770(line=31, offs=2)
*/
/*
local: 
global: create_server$1$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__create_server(atstype_funptr arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret2) ;
ATStmpdec(tmp3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp5, atstype_boxed) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 480(line=21, offs=11) -- 770(line=31, offs=2)
*/
ATSINSflab(__patsflab_create_server):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 514(line=21, offs=45) -- 770(line=31, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 537(line=22, offs=12) -- 551(line=22, offs=26)
*/
ATSINSmove(tmp3, zmq_ctx_new()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 564(line=23, offs=13) -- 589(line=23, offs=38)
*/
ATSINSmove(tmp4, zmq_socket(ATSPMVrefarg0(tmp3), ATSPMVextval(ZMQ_REP))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 605(line=24, offs=16) -- 626(line=24, offs=37)
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp5, postiats_tyrec_0) ;
ATSINSstore_boxrec_ofs (tmp5, postiats_tyrec_0, atslab__ctx, tmp3) ;
ATSINSstore_boxrec_ofs (tmp5, postiats_tyrec_0, atslab__sock, tmp4) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 637(line=25, offs=11) -- 666(line=25, offs=40)
*/
ATSINSmove(tmp6, zmq_bind(ATSPMVrefarg0(ATSSELboxrec(tmp5, postiats_tyrec_0, atslab__sock)), arg1)) ;

/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 758(line=29, offs=11) -- 766(line=29, offs=19)
*/
ATSINSmove_void(tmpret2, ATSfunclo_fun(arg0, (atstype_boxed), atsvoid_t0ype)(ATSPMVcastfn(castvwtp0, atstype_boxed, tmp5))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 514(line=21, offs=45) -- 770(line=31, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret2) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__create_server] */

/*
/home/hwwu/GitHub/ats-session-playground/session.dats: 800(line=33, offs=29) -- 1073(line=42, offs=2)
*/
/*
local: 
global: create_client$2$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__create_client(atstype_funptr arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret7) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp9, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp10, atstype_boxed) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 782(line=33, offs=11) -- 1073(line=42, offs=2)
*/
ATSINSflab(__patsflab_create_client):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 816(line=33, offs=45) -- 1073(line=42, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 838(line=34, offs=12) -- 852(line=34, offs=26)
*/
ATSINSmove(tmp8, zmq_ctx_new()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 865(line=35, offs=13) -- 890(line=35, offs=38)
*/
ATSINSmove(tmp9, zmq_socket(ATSPMVrefarg0(tmp8), ATSPMVextval(ZMQ_REQ))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 906(line=36, offs=16) -- 927(line=36, offs=37)
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp10, postiats_tyrec_0) ;
ATSINSstore_boxrec_ofs (tmp10, postiats_tyrec_0, atslab__ctx, tmp8) ;
ATSINSstore_boxrec_ofs (tmp10, postiats_tyrec_0, atslab__sock, tmp9) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 937(line=36, offs=47) -- 969(line=36, offs=79)
*/
ATSINSmove(tmp11, zmq_connect(ATSPMVrefarg0(ATSSELboxrec(tmp10, postiats_tyrec_0, atslab__sock)), arg1)) ;

/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1061(line=40, offs=11) -- 1069(line=40, offs=19)
*/
ATSINSmove_void(tmpret7, ATSfunclo_fun(arg0, (atstype_boxed), atsvoid_t0ype)(ATSPMVcastfn(castvwtp0, atstype_boxed, tmp10))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 816(line=33, offs=45) -- 1073(line=42, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret7) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__create_client] */

/*
/home/hwwu/GitHub/ats-session-playground/session.dats: 1094(line=44, offs=20) -- 1452(line=55, offs=2)
*/
/*
local: 
global: send$3$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__send(atsrefarg0_type(atstype_boxed) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret12) ;
ATStmpdec(tmpref13, zmq_msg_t) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp17) ;
ATStmpdec(tmp18, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp19, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1085(line=44, offs=11) -- 1452(line=55, offs=2)
*/
ATSINSflab(__patsflab_send):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1112(line=44, offs=38) -- 1452(line=55, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1129(line=46, offs=6) -- 1132(line=46, offs=9)
*/
/*
ATSINStmpdec(tmpref13) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1155(line=47, offs=10) -- 1189(line=47, offs=44)
*/
ATSINSmove(tmp14, ATSextfcall(strlen, (arg1))) ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1204(line=48, offs=15) -- 1210(line=48, offs=21)
*/
ATSINSmove(tmp16, atspre_g1int2uint_int_size(ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1199(line=48, offs=10) -- 1210(line=48, offs=21)
*/
ATSINSmove(tmp15, atspre_g0uint_add_size(tmp14, tmp16)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1222(line=49, offs=11) -- 1248(line=49, offs=37)
*/
ATSINSmove_void(tmp17, zmq_msg_init_size(ATSPMVrefarg1(ATSPMVptrof(tmpref13)), tmp15)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1351(line=51, offs=25) -- 1367(line=51, offs=41)
*/
ATSINSmove(tmp19, zmq_msg_data(ATSPMVrefarg1(ATSPMVptrof(tmpref13)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1336(line=51, offs=10) -- 1374(line=51, offs=48)
*/
ATSINSmove(tmp18, atslib_strcpy_unsafe(tmp19, arg1)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1385(line=52, offs=11) -- 1420(line=52, offs=46)
*/
ATSINSmove(tmp20, zmq_msg_send(ATSPMVrefarg1(ATSPMVptrof(tmpref13)), ATSPMVrefarg0(ATSSELboxrec(arg0, postiats_tyrec_0, atslab__sock)), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1431(line=53, offs=11) -- 1448(line=53, offs=28)
*/
ATSINSmove_void(tmpret12, zmq_msg_close(ATSPMVrefarg1(ATSPMVptrof(tmpref13)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1112(line=44, offs=38) -- 1452(line=55, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret12) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__send] */

/*
/home/hwwu/GitHub/ats-session-playground/session.dats: 1476(line=57, offs=23) -- 1923(line=71, offs=2)
*/
/*
local: 
global: receive$5$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__receive(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref22, zmq_msg_t) ;
// ATStmpdec_void(tmp23) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp25, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp44, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp46) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1464(line=57, offs=11) -- 1923(line=71, offs=2)
*/
ATSINSflab(__patsflab_receive):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1488(line=57, offs=35) -- 1923(line=71, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1507(line=59, offs=6) -- 1510(line=59, offs=9)
*/
/*
ATSINStmpdec(tmpref22) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1534(line=60, offs=11) -- 1551(line=60, offs=28)
*/
ATSINSmove_void(tmp23, zmq_msg_init(ATSPMVrefarg1(ATSPMVptrof(tmpref22)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1563(line=61, offs=11) -- 1598(line=61, offs=46)
*/
ATSINSmove(tmp24, zmq_msg_recv(ATSPMVrefarg1(ATSPMVptrof(tmpref22)), ATSPMVrefarg0(ATSSELboxrec(arg0, postiats_tyrec_0, atslab__sock)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1759(line=67, offs=13) -- 1780(line=67, offs=34)
*/
ATSINSmove(tmp25, ATSLIB_056_prelude__string0_copy__6__1(ATSPMVstring("_____"))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1841(line=68, offs=60) -- 1857(line=68, offs=76)
*/
ATSINSmove(tmp45, zmq_msg_data(ATSPMVrefarg1(ATSPMVptrof(tmpref22)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1791(line=68, offs=10) -- 1859(line=68, offs=78)
*/
ATSINSmove(tmp44, atslib_strcpy_unsafe(ATSPMVcastfn(strptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp25)), ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp45))) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1903(line=70, offs=11) -- 1920(line=70, offs=28)
*/
ATSINSmove_void(tmp46, zmq_msg_close(ATSPMVrefarg1(ATSPMVptrof(tmpref22)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1488(line=57, offs=35) -- 1492(line=57, offs=39)
*/
ATSINSmove(tmpret21, ATSPMVcastfn(strptr2string, atstkind_type(atstype_ptrk), tmp25)) ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/session.dats: 1488(line=57, offs=35) -- 1923(line=71, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret21) ;
} /* end of [_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_sats__receive] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 7634(line=341, offs=3) -- 7772(line=349, offs=4)
*/
/*
local: 
global: string0_copy$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_copy__6(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp27, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7619(line=340, offs=1) -- 7772(line=349, offs=4)
*/
ATSINSflab(__patsflab_string0_copy):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7642(line=341, offs=11) -- 7772(line=349, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7682(line=344, offs=12) -- 7699(line=344, offs=29)
*/
ATSINSmove(tmp27, PMVtmpltcst(string1_copy<>)(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7747(line=348, offs=3) -- 7767(line=348, offs=23)
*/
ATSINSmove(tmpret26, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp27)) ;
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7642(line=341, offs=11) -- 7772(line=349, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret26) ;
} /* end of [ATSLIB_056_prelude__string0_copy__6] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 7634(line=341, offs=3) -- 7772(line=349, offs=4)
*/
/*
local: 
global: string0_copy$6$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string0_copy__6__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp27__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7619(line=340, offs=1) -- 7772(line=349, offs=4)
*/
ATSINSflab(__patsflab_string0_copy):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7642(line=341, offs=11) -- 7772(line=349, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7682(line=344, offs=12) -- 7699(line=344, offs=29)
*/
ATSINSmove(tmp27__1, ATSLIB_056_prelude__string1_copy__8__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7747(line=348, offs=3) -- 7767(line=348, offs=23)
*/
ATSINSmove(tmpret26__1, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp27__1)) ;
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7642(line=341, offs=11) -- 7772(line=349, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret26__1) ;
} /* end of [ATSLIB_056_prelude__string0_copy__6__1] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 7830(line=353, offs=7) -- 8041(line=362, offs=4)
*/
/*
local: 
global: string1_copy$8$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_copy__8(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp33, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp34, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp35, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7811(line=352, offs=1) -- 8041(line=362, offs=4)
*/
ATSINSflab(__patsflab_string1_copy):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7838(line=353, offs=15) -- 8041(line=362, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7853(line=355, offs=9) -- 7872(line=355, offs=28)
*/
ATSINSmove(tmp31, PMVtmpltcst(string1_length<>)(arg0)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7883(line=356, offs=10) -- 7889(line=356, offs=16)
*/
ATSINSmove(tmp32, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(tmp31)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7912(line=357, offs=22) -- 7925(line=357, offs=35)
*/
ATSINSmove(tmp33, atspre_malloc_gc(tmp32)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7954(line=358, offs=28) -- 7985(line=358, offs=59)
*/
ATSINSmove(tmp34, atspre_string_memcpy(tmp33, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp32)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 8021(line=361, offs=29) -- 8037(line=361, offs=45)
*/
ATSINSmove(tmp35, tmp33) ;
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7995(line=361, offs=3) -- 8037(line=361, offs=45)
*/
ATSINSmove(tmpret30, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp35)) ;
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7838(line=353, offs=15) -- 8041(line=362, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret30) ;
} /* end of [ATSLIB_056_prelude__string1_copy__8] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 7830(line=353, offs=7) -- 8041(line=362, offs=4)
*/
/*
local: 
global: string1_copy$8$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string1_copy__8__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp31__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp32__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp33__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp34__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp35__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7811(line=352, offs=1) -- 8041(line=362, offs=4)
*/
ATSINSflab(__patsflab_string1_copy):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7838(line=353, offs=15) -- 8041(line=362, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7853(line=355, offs=9) -- 7872(line=355, offs=28)
*/
ATSINSmove(tmp31__1, ATSLIB_056_prelude__string1_length__10__1(arg0)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7883(line=356, offs=10) -- 7889(line=356, offs=16)
*/
ATSINSmove(tmp32__1, atspre_g1uint_succ_size(tmp31__1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7912(line=357, offs=22) -- 7925(line=357, offs=35)
*/
ATSINSmove(tmp33__1, atspre_malloc_gc(tmp32__1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7954(line=358, offs=28) -- 7985(line=358, offs=59)
*/
ATSINSmove(tmp34__1, atspre_string_memcpy(tmp33__1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), tmp32__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 8021(line=361, offs=29) -- 8037(line=361, offs=45)
*/
ATSINSmove(tmp35__1, tmp33__1) ;
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7995(line=361, offs=3) -- 8037(line=361, offs=45)
*/
ATSINSmove(tmpret30__1, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp35__1)) ;
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7838(line=353, offs=15) -- 8041(line=362, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret30__1) ;
} /* end of [ATSLIB_056_prelude__string1_copy__8__1] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 7431(line=332, offs=7) -- 7539(line=335, offs=2)
*/
/*
local: 
global: string1_length$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__10(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret42, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7410(line=331, offs=1) -- 7539(line=335, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7441(line=333, offs=3) -- 7539(line=335, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7441(line=333, offs=3) -- 7454(line=333, offs=16)
*/
ATSINSmove(tmpret42, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7441(line=333, offs=3) -- 7539(line=335, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret42) ;
} /* end of [ATSLIB_056_prelude__string1_length__10] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 7431(line=332, offs=7) -- 7539(line=335, offs=2)
*/
/*
local: 
global: string1_length$10$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__10__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret42__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7410(line=331, offs=1) -- 7539(line=335, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7441(line=333, offs=3) -- 7539(line=335, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7441(line=333, offs=3) -- 7454(line=333, offs=16)
*/
ATSINSmove(tmpret42__1, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 7441(line=333, offs=3) -- 7539(line=335, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret42__1) ;
} /* end of [ATSLIB_056_prelude__string1_length__10__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_session_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
