/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-3-30: 17h:48m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/hwwu/GitHub/ats-session-playground/zmq.sats: 3(line=3, offs=1) -- 61(line=8, offs=3)
*/

#ifndef __ZMQ
#define __ZMQ
#include <zmq.h>
#endif
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(zmq_msg_init_size)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(zmq_msg_data)
ATSdyncst_mac(zmq_msg_send)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(zmq_errno)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_mac(atspre_g0int2uint_int_size)
ATSdyncst_mac(atspre_g0uint_eq_size)
ATSdyncst_mac(zmq_msg_close)
ATSdyncst_mac(zmq_msg_init)
ATSdyncst_mac(zmq_msg_recv)
ATSdyncst_mac(zmq_version)
ATSdyncst_mac(zmq_ctx_new)
ATSdyncst_mac(zmq_socket)
ATSdyncst_mac(zmq_connect)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(zmq_close)
ATSdyncst_mac(zmq_ctx_term)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
loop_1(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0uint_int__3(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0uint_int__3__1(atstkind_t0ype(atstype_size), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 137(line=6, offs=17) -- 1305(line=45, offs=2)
*/
/*
local: 
global: mainats_void_0$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmpref1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref3, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp30) ;
// ATStmpdec_void(tmp31) ;
// ATStmpdec_void(tmp32) ;
// ATStmpdec_void(tmp33) ;
// ATStmpdec_void(tmp34) ;
// ATStmpdec_void(tmp35) ;
// ATStmpdec_void(tmp36) ;
// ATStmpdec_void(tmp37) ;
ATStmpdec(tmp38, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp39, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp40) ;
// ATStmpdec_void(tmp41) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp43) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp45) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp51) ;
// ATStmpdec_void(tmp52) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp54) ;
// ATStmpdec_void(tmp55) ;
// ATStmpdec_void(tmp56) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 131(line=6, offs=11) -- 1305(line=45, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 142(line=6, offs=22) -- 1305(line=45, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 159(line=7, offs=7) -- 164(line=7, offs=12)
*/
/*
ATSINStmpdec(tmpref1) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 176(line=8, offs=7) -- 181(line=8, offs=12)
*/
/*
ATSINStmpdec(tmpref2) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 193(line=9, offs=7) -- 198(line=9, offs=12)
*/
/*
ATSINStmpdec(tmpref3) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 851(line=29, offs=12) -- 883(line=29, offs=44)
*/
ATSINSmove_void(tmp30, zmq_version(ATSPMVrefarg1(ATSPMVptrof(tmpref1)), ATSPMVrefarg1(ATSPMVptrof(tmpref2)), ATSPMVrefarg1(ATSPMVptrof(tmpref3)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp31, atspre_print_string(ATSPMVstring("Installed ZeroMQ version: "))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp32, atspre_print_int(tmpref1)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp33, atspre_print_string(ATSPMVstring("."))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp34, atspre_print_int(tmpref2)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp35, atspre_print_string(ATSPMVstring("."))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp36, atspre_print_int(tmpref3)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 895(line=30, offs=12) -- 965(line=30, offs=82)
*/
ATSINSmove_void(tmp37, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 979(line=32, offs=13) -- 992(line=32, offs=26)
*/
ATSINSmove(tmp38, zmq_ctx_new()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1008(line=33, offs=16) -- 1033(line=33, offs=41)
*/
ATSINSmove(tmp39, zmq_socket(ATSPMVrefarg0(tmp38), ATSPMVextval(ZMQ_REQ))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1045(line=34, offs=12) -- 1080(line=34, offs=47)
*/
ATSINSmove_void(tmp40, atspre_print_string(ATSPMVstring("errno = "))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1067(line=34, offs=34) -- 1079(line=34, offs=46)
*/
ATSINSmove(tmp42, zmq_errno()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1045(line=34, offs=12) -- 1080(line=34, offs=47)
*/
ATSINSmove_void(tmp41, atspre_print_int(tmp42)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1045(line=34, offs=12) -- 1080(line=34, offs=47)
*/
ATSINSmove_void(tmp43, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1093(line=36, offs=12) -- 1137(line=36, offs=56)
*/
ATSINSmove(tmp44, zmq_connect(ATSPMVrefarg0(tmp39), ATSPMVstring("tcp://localhost:9999"))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1148(line=37, offs=11) -- 1165(line=37, offs=28)
*/
ATSINSmove(tmp46, ATSLIB_056_prelude__eq_g0int_int__7__1(tmp44, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1148(line=37, offs=11) -- 1165(line=37, offs=28)
*/
ATSINSmove_void(tmp45, atspre_assert_errmsg_bool0(tmp46, ATSCSTSPmyloc("/home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1148(line=37, offs=11) -- 1165(line=37, offs=28)"))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1178(line=38, offs=12) -- 1213(line=38, offs=47)
*/
ATSINSmove_void(tmp51, atspre_print_string(ATSPMVstring("errno = "))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1200(line=38, offs=34) -- 1212(line=38, offs=46)
*/
ATSINSmove(tmp53, zmq_errno()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1178(line=38, offs=12) -- 1213(line=38, offs=47)
*/
ATSINSmove_void(tmp52, atspre_print_int(tmp53)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1178(line=38, offs=12) -- 1213(line=38, offs=47)
*/
ATSINSmove_void(tmp54, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1226(line=40, offs=12) -- 1238(line=40, offs=24)
*/
ATSINSmove_void(tmp55, loop_1(ATSPMVrefarg0(tmp39))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1255(line=43, offs=12) -- 1272(line=43, offs=29)
*/
ATSINSmove_void(tmp56, zmq_close(tmp39)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 1285(line=44, offs=12) -- 1302(line=44, offs=29)
*/
ATSINSmove_void(tmpret0, zmq_ctx_term(tmp38)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 142(line=6, offs=22) -- 1305(line=45, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [mainats_void_0] */

/*
/home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 213(line=11, offs=7) -- 836(line=27, offs=4)
*/
/*
local: 
global: loop_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret4) ;
ATStmpdec(tmpref5, zmq_msg_t) ;
// ATStmpdec_void(tmp6) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp8) ;
ATStmpdec(tmp9, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp11) ;
// ATStmpdec_void(tmp12) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp14) ;
// ATStmpdec_void(tmp15) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp21) ;
// ATStmpdec_void(tmp22) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp24) ;
// ATStmpdec_void(tmp25) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp27) ;
// ATStmpdec_void(tmp28) ;
ATStmpdec(tmp29, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 213(line=11, offs=7) -- 836(line=27, offs=4)
*/
ATSINSflab(__patsflab_loop_1):
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 270(line=11, offs=64) -- 836(line=27, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 291(line=12, offs=11) -- 294(line=12, offs=14)
*/
/*
ATSINStmpdec(tmpref5) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 353(line=14, offs=40) -- 360(line=14, offs=47)
*/
ATSINSmove(tmp7, atspre_g1int2uint_int_size(ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 329(line=14, offs=16) -- 361(line=14, offs=48)
*/
ATSINSmove_void(tmp6, zmq_msg_init_size(ATSPMVrefarg1(ATSPMVptrof(tmpref5)), tmp7)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 404(line=15, offs=43) -- 421(line=15, offs=60)
*/
ATSINSmove(tmp9, zmq_msg_data(ATSPMVrefarg1(ATSPMVptrof(tmpref5)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 377(line=15, offs=16) -- 437(line=15, offs=76)
*/
ATSINSmove_void(tmp8, ATSextfcall(memcpy, (tmp9, ATSPMVstring("hello"), ATSPMVi0nt(6)))) ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 452(line=16, offs=15) -- 481(line=16, offs=44)
*/
ATSINSmove(tmp10, zmq_msg_send(ATSPMVrefarg1(ATSPMVptrof(tmpref5)), ATSPMVrefarg0(arg0), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 497(line=17, offs=16) -- 532(line=17, offs=51)
*/
ATSINSmove_void(tmp11, atspre_print_string(ATSPMVstring("errno = "))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 519(line=17, offs=38) -- 531(line=17, offs=50)
*/
ATSINSmove(tmp13, zmq_errno()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 497(line=17, offs=16) -- 532(line=17, offs=51)
*/
ATSINSmove_void(tmp12, atspre_print_int(tmp13)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 497(line=17, offs=16) -- 532(line=17, offs=51)
*/
ATSINSmove_void(tmp14, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 547(line=18, offs=15) -- 563(line=18, offs=31)
*/
ATSINSmove(tmp16, ATSLIB_056_prelude__eq_g0uint_int__3__1(tmp10, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 547(line=18, offs=15) -- 563(line=18, offs=31)
*/
ATSINSmove_void(tmp15, atspre_assert_errmsg_bool0(tmp16, ATSCSTSPmyloc("/home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 547(line=18, offs=15) -- 563(line=18, offs=31)"))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 580(line=19, offs=16) -- 598(line=19, offs=34)
*/
ATSINSmove_void(tmp21, zmq_msg_close(ATSPMVrefarg1(ATSPMVptrof(tmpref5)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 616(line=21, offs=16) -- 633(line=21, offs=33)
*/
ATSINSmove_void(tmp22, zmq_msg_init(ATSPMVrefarg1(ATSPMVptrof(tmpref5)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 649(line=22, offs=15) -- 678(line=22, offs=44)
*/
ATSINSmove(tmp23, zmq_msg_recv(ATSPMVrefarg1(ATSPMVptrof(tmpref5)), ATSPMVrefarg0(arg0), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 694(line=23, offs=16) -- 729(line=23, offs=51)
*/
ATSINSmove_void(tmp24, atspre_print_string(ATSPMVstring("errno = "))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 716(line=23, offs=38) -- 728(line=23, offs=50)
*/
ATSINSmove(tmp26, zmq_errno()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 694(line=23, offs=16) -- 729(line=23, offs=51)
*/
ATSINSmove_void(tmp25, atspre_print_int(tmp26)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 694(line=23, offs=16) -- 729(line=23, offs=51)
*/
ATSINSmove_void(tmp27, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 777(line=24, offs=48) -- 794(line=24, offs=65)
*/
ATSINSmove(tmp29, zmq_msg_data(ATSPMVrefarg1(ATSPMVptrof(tmpref5)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 744(line=24, offs=15) -- 796(line=24, offs=67)
*/
ATSINSmove_void(tmp28, ATSextfcall(printf, (ATSPMVstring("%s"), tmp29))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 812(line=25, offs=16) -- 830(line=25, offs=34)
*/
ATSINSmove_void(tmpret4, zmq_msg_close(ATSPMVrefarg1(ATSPMVptrof(tmpref5)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/ats-session-playground/zmqclient.dats: 270(line=11, offs=64) -- 836(line=27, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret4) ;
} /* end of [loop_1] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 30144(line=838, offs=15) -- 30186(line=838, offs=57)
*/
/*
local: 
global: eq_g0uint_int$3$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4469)
tmparg = S2Evar(tk(4469))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0uint_int__3(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30130(line=838, offs=1) -- 30186(line=838, offs=57)
*/
ATSINSflab(__patsflab_eq_g0uint_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30171(line=838, offs=42) -- 30184(line=838, offs=55)
*/
ATSINSmove(tmp18, PMVtmpltcst(g0int2uint<S2Eextkind(atstype_int), S2Evar(tk(4469))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30153(line=838, offs=24) -- 30186(line=838, offs=57)
*/
ATSINSmove(tmpret17, PMVtmpltcst(g0uint_eq<S2Evar(tk(4469))>)(arg0, tmp18)) ;

ATSfunbody_end()
ATSreturn(tmpret17) ;
} /* end of [ATSLIB_056_prelude__eq_g0uint_int__3] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 30144(line=838, offs=15) -- 30186(line=838, offs=57)
*/
/*
local: 
global: eq_g0uint_int$3$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4469)
tmparg = S2Evar(tk(4469))
tmpsub = Some(tk(4469) -> S2Eextkind(atstype_size))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0uint_int__3__1(atstkind_t0ype(atstype_size) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret17__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp18__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30130(line=838, offs=1) -- 30186(line=838, offs=57)
*/
ATSINSflab(__patsflab_eq_g0uint_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30171(line=838, offs=42) -- 30184(line=838, offs=55)
*/
ATSINSmove(tmp18__1, atspre_g0int2uint_int_size(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 30153(line=838, offs=24) -- 30186(line=838, offs=57)
*/
ATSINSmove(tmpret17__1, atspre_g0uint_eq_size(arg0, tmp18__1)) ;

ATSfunbody_end()
ATSreturn(tmpret17__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0uint_int__3__1] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret47, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp48, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp48, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4441))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret47, PMVtmpltcst(g0int_eq<S2Evar(tk(4441))>)(arg0, tmp48)) ;

ATSfunbody_end()
ATSreturn(tmpret47) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$7$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = Some(tk(4441) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret47__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp48__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp48__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret47__1, atspre_g0int_eq_int(arg0, tmp48__1)) ;

ATSfunbody_end()
ATSreturn(tmpret47__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__7__1] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_zmqclient_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_zmqclient_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_zmqclient_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_zmqclient_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_zmqclient_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_hwwu_057_GitHub_057_ats_055_session_055_playground_057_zmqclient_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
