/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-12-4: 11h:24m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/SATS/print.sats: 186(line=14, offs=1) -- 216(line=14, offs=31)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/print.dats: 294(line=22, offs=1) -- 324(line=22, offs=31)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/print.dats: 328(line=24, offs=1) -- 358(line=24, offs=31)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/SATS/print.sats: 186(line=14, offs=1) -- 216(line=14, offs=31)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/intrange.dats: 359(line=27, offs=1) -- 391(line=28, offs=25)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/intrange.dats: 395(line=30, offs=1) -- 429(line=31, offs=27)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/intrange.dats: 433(line=33, offs=1) -- 462(line=33, offs=30)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/SATS/list.sats: 259(line=21, offs=1) -- 289(line=21, offs=31)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/intrange.dats: 489(line=37, offs=1) -- 522(line=37, offs=34)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/SATS/list.sats: 259(line=21, offs=1) -- 289(line=21, offs=31)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/list.dats: 355(line=27, offs=1) -- 394(line=28, offs=32)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/list.dats: 421(line=32, offs=1) -- 453(line=32, offs=33)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/DATS/list.dats: 480(line=36, offs=1) -- 509(line=36, offs=30)
*/
/*
/Users/hwwu/Programs/ats-contrib/contrib/libatscc/libatscc2erl/SATS/list.sats: 259(line=21, offs=1) -- 289(line=21, offs=31)
*/
/*
/Users/hwwu/Git/ats-session-playground/session/session.sats: 56(line=4, offs=1) -- 111(line=4, offs=56)
*/
/*
staload-prologues(end)
*/
/*
/Users/hwwu/Git/ats-session-playground/session/test/counter.dats: 172(line=9, offs=1) -- 423(line=21, offs=3)
*/
ATSextcode_beg()
%%
-module(counter).
%%
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(export_all).
-compile(debug_info).
%%
-include("$PATSHOMERELOC/contrib/libatscc/libatscc2erl/libatscc2erl_all.hrl").
-include("../session.hrl").
%%
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
/Users/hwwu/Git/ats-session-playground/session/test/counter.dats: 465(line=24, offs=1) -- 523(line=24, offs=59)
*/
ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__stream) ;
/*
/Users/hwwu/Git/ats-session-playground/session/test/counter.dats: 554(line=27, offs=1) -- 620(line=27, offs=67)
*/
ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__dualstream) ;
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_test_057_counter_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
