/*
**
** The C code is generated by [ATS/Postiats-0-3-5]
** The starting compilation time is: 2017-4-20: 17h: 3m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_type(atstype_ptrk) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(libsession__spawn_link)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
libsession__create(atstype_cloptr) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
__patsfun_1(atstype_cloptr, atstkind_type(atstype_ptrk)) ;

ATSclosurerize_beg(__patsfun_1, (atstype_cloptr, atstkind_type(atstype_ptrk)), (), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
atstype_cloptr env0 ;
atstkind_type(atstype_ptrk) env1 ;
} __patsfun_1__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_1__cfun
(
__patsfun_1__closure_t0ype *p_cenv
)
{
ATSFCreturn_void(__patsfun_1(p_cenv->env0, p_cenv->env1)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_1__closureinit
(
__patsfun_1__closure_t0ype *p_cenv, atstype_cloptr env0, atstkind_type(atstype_ptrk) env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_1__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_1__closurerize
(
atstype_cloptr env0, atstkind_type(atstype_ptrk) env1
)
{
return __patsfun_1__closureinit(ATS_MALLOC(sizeof(__patsfun_1__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 165(line=8, offs=30) -- 456(line=22, offs=4)
*/
/*
local: 
global: libsession__create$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
libsession__create(atstype_cloptr arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp1, atstype_boxed) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 146(line=8, offs=11) -- 456(line=22, offs=4)
*/
ATSINSflab(__patsflab_create):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 171(line=8, offs=36) -- 456(line=22, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 196(line=10, offs=20) -- 254(line=10, offs=78)
*/
ATSINSmove(tmp1, ATSextfcall(libsession__create, ())) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 184(line=10, offs=8) -- 187(line=10, offs=11)
*/
ATSINSmove(tmp2, ATSSELboxrec(tmp1, postiats_tyrec_0, atslab__0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 189(line=10, offs=13) -- 192(line=10, offs=16)
*/
ATSINSmove(tmp3, ATSSELboxrec(tmp1, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 329(line=14, offs=10) -- 441(line=18, offs=11)
*/
ATSINSmove_void(tmp4, libsession__spawn_link(ATSPMVcfunlab(1, __patsfun_1, (arg0, tmp2)))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 449(line=21, offs=2) -- 452(line=21, offs=5)
*/
ATSINSmove(tmpret0, tmp3) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 171(line=8, offs=36) -- 456(line=22, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [libsession__create] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 341(line=14, offs=22) -- 440(line=18, offs=10)
*/
/*
local: 
global: __patsfun_1$0(level=1)
local: f$70(1)(HSEfun(CLO(1); HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))); HSEcst(atsvoid_t0ype))), pos$71(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: f$70(1)(HSEfun(CLO(1); HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))); HSEcst(atsvoid_t0ype))), pos$71(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_1(atstype_cloptr env0, atstkind_type(atstype_ptrk) env1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret5) ;
// ATStmpdec_void(tmp6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 341(line=14, offs=22) -- 440(line=18, offs=10)
*/
ATSINSflab(__patsflab___patsfun_1):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 360(line=14, offs=41) -- 440(line=18, offs=10)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 380(line=15, offs=16) -- 385(line=15, offs=21)
*/
ATSINSmove_void(tmp6, ATSfunclo_clo(ATSPMVrefarg0(env0), (atstype_cloptr, atstkind_type(atstype_ptrk)), atsvoid_t0ype)(ATSPMVrefarg0(env0), env1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 427(line=17, offs=7) -- 440(line=18, offs=10)
*/
ATSINSmove_void(tmpret5, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/session.dats: 360(line=14, offs=41) -- 440(line=18, offs=10)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret5) ;
} /* end of [__patsfun_1] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_session_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_session_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_session_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_session_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_session_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
