/*
**
** The C code is generated by [ATS/Postiats-0-3-5]
** The starting compilation time is: 2017-4-20: 17h: 3m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/print.sats: 186(line=14, offs=1) -- 216(line=14, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/print.dats: 294(line=22, offs=1) -- 324(line=22, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/print.dats: 328(line=24, offs=1) -- 358(line=24, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/print.sats: 186(line=14, offs=1) -- 216(line=14, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/intrange.sats: 294(line=23, offs=1) -- 324(line=23, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/intrange.dats: 392(line=29, offs=1) -- 422(line=29, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/intrange.dats: 449(line=33, offs=1) -- 478(line=33, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/list.sats: 292(line=23, offs=1) -- 322(line=23, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/intrange.dats: 482(line=35, offs=1) -- 514(line=35, offs=33)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/intrange.dats: 518(line=37, offs=1) -- 551(line=37, offs=34)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/intrange.sats: 294(line=23, offs=1) -- 324(line=23, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/list.sats: 292(line=23, offs=1) -- 322(line=23, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/list.dats: 388(line=29, offs=1) -- 427(line=30, offs=32)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/list.dats: 454(line=34, offs=1) -- 483(line=34, offs=30)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/SATS/list.sats: 292(line=23, offs=1) -- 322(line=23, offs=31)
*/
/*
/Users/hwwu/Programs/atsgit/contrib/libatscc2erl/ATS2-0.3.2/DATS/list.dats: 510(line=38, offs=1) -- 542(line=38, offs=33)
*/
/*
staload-prologues(end)
*/
/*
/Users/hwwu/Git/ats-session-playground/dependent/output/teststub.dats: 111(line=7, offs=1) -- 350(line=15, offs=3)
*/
ATSextcode_beg()
-module(test).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(export_all).
-compile(debug_info).
-include("$PATSHOME/contrib/libatscc2erl/ATS2-0.3.2/output/libatscc2erl_all.hrl").
-include("./session.hrl").
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyrec_0 ;
typedef
ATSstruct {
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tyrec_1 ;
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tyrec_2 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(libsession__offer)
ATSdyncst_mac(libsession__close)
ATSdyncst_mac(libsession__recv)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem, (atstkind_type(atstype_ptrk), atstyvar_type(a)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(libsession__cut)
ATSdyncst_mac(libsession__create)
ATSdyncst_mac(libsession__send)
ATSdyncst_mac(libsession__choose)
ATSdyncst_mac(ats2erlpre_add_int1_int1)
ATSdyncst_mac(ats2erlpre_sub_int1_int1)
ATSdyncst_mac(libsession__wait)
ATSdyncst_mac(ats2erlpre_eq_int1_int1)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len, (atsrefarg0_type(atstype_boxed)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(ats2erlpre_print_string)
ATSdyncst_mac(ats2erlpre_print_newline)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free, (atstype_boxed), atsvoid_t0ype) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq, (atstype_boxed), atstype_boxed) ;
ATSdyncst_mac(ats2erlpre_print_int)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall, (atstype_boxed), atsvoid_t0ype) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil, (), atstype_boxed) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq, (atstype_boxed, atstyvar_type(a)), atstype_boxed) ;
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test, (), atsvoid_t0ype) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
server_1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atsvoid_t0ype
__patsfun_2(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem(atstkind_type(atstype_ptrk), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
server_4(atstyvar_type(a), atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk)) ;

ATSstatic()
atsvoid_t0ype
__patsfun_5(atstkind_type(atstype_ptrk), atstyvar_type(a), atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(atstype_boxed, atstyvar_type(a)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(atstype_boxed) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
r() ;
#endif // end of [QUALIFIED]

ATSclosurerize_beg(__patsfun_2, (), (atstkind_type(atstype_ptrk)), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
} __patsfun_2__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_2__cfun
(
__patsfun_2__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) arg0
)
{
ATSFCreturn_void(__patsfun_2(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_2__closureinit
(
__patsfun_2__closure_t0ype *p_cenv
)
{
p_cenv->cfun = __patsfun_2__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_2__closurerize
(
// argumentless
)
{
return __patsfun_2__closureinit(ATS_MALLOC(sizeof(__patsfun_2__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(__patsfun_5, (atstkind_type(atstype_ptrk), atstyvar_type(a)), (atstkind_type(atstype_ptrk)), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
atstkind_type(atstype_ptrk) env0 ;
atstyvar_type(a) env1 ;
} __patsfun_5__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
__patsfun_5__cfun
(
__patsfun_5__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) arg0
)
{
ATSFCreturn_void(__patsfun_5(p_cenv->env0, p_cenv->env1, arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
__patsfun_5__closureinit
(
__patsfun_5__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) env0, atstyvar_type(a) env1
)
{
p_cenv->env0 = env0 ;
p_cenv->env1 = env1 ;
p_cenv->cfun = __patsfun_5__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
__patsfun_5__closurerize
(
atstkind_type(atstype_ptrk) env0, atstyvar_type(a) env1
)
{
return __patsfun_5__closureinit(ATS_MALLOC(sizeof(__patsfun_5__closure_t0ype)), env0, env1) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 447(line=17, offs=21) -- 850(line=41, offs=4)
*/
/*
local: 
global: empty$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 437(line=17, offs=11) -- 850(line=41, offs=4)
*/
ATSINSflab(__patsflab_empty):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 452(line=17, offs=26) -- 850(line=41, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 815(line=40, offs=2) -- 846(line=40, offs=33)
*/
ATSINSmove(tmpret0, libsession__create(ATSPMVcfunlab(1, __patsfun_2, ()))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 452(line=17, offs=26) -- 850(line=41, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 462(line=18, offs=6) -- 808(line=37, offs=5)
*/
/*
local: 
global: server_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
server_1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret1) ;
ATStmpdec(tmp2, atstype_boxed) ;
ATStmpdec(tmp3, atstyvar_type(a)) ;
ATStmpdec(tmp4, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp5, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 462(line=18, offs=6) -- 808(line=37, offs=5)
*/
ATSINSflab(__patsflab_server_1):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 504(line=18, offs=48) -- 808(line=37, offs=5)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 550(line=20, offs=16) -- 559(line=20, offs=25)
*/
ATSINSmove(tmp2, libsession__offer(ATSPMVrefarg0(arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 567(line=22, offs=3) -- 803(line=36, offs=7)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 588(line=23, offs=5) -- 597(line=23, offs=14)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 550(line=20, offs=16) -- 559(line=20, offs=25)
*/
ATSifnthen(ATSCKpat_con0(tmp2, 1)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 597(line=23, offs=14) -- 597(line=23, offs=14)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 645(line=27, offs=5) -- 654(line=27, offs=14)
*/
ATSINSmove_void(tmpret1, libsession__close(arg0)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 666(line=29, offs=5) -- 674(line=29, offs=13)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 550(line=20, offs=16) -- 559(line=20, offs=25)
*/
#if(0)
ATSifnthen(ATSCKpat_con0(tmp2, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 674(line=29, offs=13) -- 674(line=29, offs=13)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 683(line=30, offs=4) -- 803(line=36, offs=7)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 700(line=31, offs=13) -- 708(line=31, offs=21)
*/
ATSINSmove(tmp3, libsession__recv(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 725(line=32, offs=16) -- 737(line=32, offs=28)
*/
ATSINSmove(tmp4, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 752(line=33, offs=15) -- 770(line=33, offs=33)
*/
ATSINSmove(tmp5, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem(tmp4, tmp3)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 782(line=35, offs=5) -- 796(line=35, offs=19)
*/
ATSINSmove_void(tmpret1, libsession__cut(tmp5, arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 683(line=30, offs=4) -- 803(line=36, offs=7)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 504(line=18, offs=48) -- 808(line=37, offs=5)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [server_1] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 823(line=40, offs=10) -- 845(line=40, offs=32)
*/
/*
local: server_1$0(level=1)
global: server_1$0(level=1), __patsfun_2$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
__patsfun_2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 823(line=40, offs=10) -- 845(line=40, offs=32)
*/
ATSINSflab(__patsflab___patsfun_2):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 835(line=40, offs=22) -- 845(line=40, offs=32)
*/
ATSINSmove_void(tmpret6, server_1(arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret6) ;
} /* end of [__patsfun_2] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 876(line=44, offs=24) -- 1387(line=69, offs=4)
*/
/*
local: 
global: elem$3$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 863(line=44, offs=11) -- 1387(line=69, offs=4)
*/
ATSINSflab(__patsflab_elem):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 890(line=44, offs=38) -- 1387(line=69, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1343(line=68, offs=2) -- 1383(line=68, offs=42)
*/
ATSINSmove(tmpret7, libsession__create(ATSPMVcfunlab(1, __patsfun_5, (arg0, arg1)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 890(line=44, offs=38) -- 1387(line=69, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 900(line=45, offs=6) -- 1337(line=66, offs=5)
*/
/*
local: server_4$0(level=1)
global: server_4$0(level=1)
local: e$440(1)(HSEtyvar(a(5036)))
global: e$440(1)(HSEtyvar(a(5036)))
*/
ATSstatic()
atsvoid_t0ype
server_4(atstyvar_type(a) env0, atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
ATStmpdec(tmp9, atstype_boxed) ;
// ATStmpdec_void(tmp10) ;
ATStmpdec(tmp11, atstyvar_type(a)) ;
// ATStmpdec_void(tmp12) ;
ATStmpdec(tmp13, atstype_boxed) ;
// ATStmpdec_void(tmp14) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 900(line=45, offs=6) -- 1337(line=66, offs=5)
*/
ATSINSflab(__patsflab_server_4):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 978(line=45, offs=84) -- 1337(line=66, offs=5)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1024(line=47, offs=16) -- 1033(line=47, offs=25)
*/
ATSINSmove(tmp9, libsession__offer(ATSPMVrefarg0(arg0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1041(line=49, offs=3) -- 1332(line=65, offs=7)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1062(line=50, offs=5) -- 1070(line=50, offs=13)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1024(line=47, offs=16) -- 1033(line=47, offs=25)
*/
ATSifnthen(ATSCKpat_con0(tmp9, 1)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1070(line=50, offs=13) -- 1070(line=50, offs=13)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1078(line=51, offs=4) -- 1164(line=56, offs=7)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1118(line=53, offs=13) -- 1131(line=53, offs=26)
*/
ATSINSmove_void(tmp10, libsession__send(ATSPMVrefarg0(arg0), env0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1143(line=55, offs=5) -- 1157(line=55, offs=19)
*/
ATSINSmove_void(tmpret8, libsession__cut(arg0, arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1078(line=51, offs=4) -- 1164(line=56, offs=7)
*/
/*
INSletpop()
*/
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1169(line=57, offs=5) -- 1176(line=57, offs=12)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1024(line=47, offs=16) -- 1033(line=47, offs=25)
*/
#if(0)
ATSifnthen(ATSCKpat_con0(tmp9, 0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1176(line=57, offs=12) -- 1176(line=57, offs=12)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1184(line=58, offs=4) -- 1332(line=65, offs=7)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1201(line=59, offs=13) -- 1209(line=59, offs=21)
*/
ATSINSmove(tmp11, libsession__recv(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1263(line=61, offs=26) -- 1269(line=61, offs=32)
*/

ATSINSmove_con0(tmp13, 0) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1250(line=61, offs=13) -- 1270(line=61, offs=33)
*/
ATSINSmove_void(tmp12, libsession__choose(ATSPMVrefarg0(arg1), tmp13)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1283(line=62, offs=13) -- 1296(line=62, offs=26)
*/
ATSINSmove_void(tmp14, libsession__send(ATSPMVrefarg0(arg1), tmp11)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1308(line=64, offs=5) -- 1325(line=64, offs=22)
*/
ATSINSmove_void(tmpret8, server_4(env0, arg0, arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1184(line=58, offs=4) -- 1332(line=65, offs=7)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 978(line=45, offs=84) -- 1337(line=66, offs=5)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [server_4] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1351(line=68, offs=10) -- 1382(line=68, offs=41)
*/
/*
local: server_4$0(level=1)
global: server_4$0(level=1), __patsfun_5$0(level=1)
local: queue$439(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), e$440(1)(HSEtyvar(a(5036)))
global: queue$439(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk)))), e$440(1)(HSEtyvar(a(5036)))
*/
ATSstatic()
atsvoid_t0ype
__patsfun_5(atstkind_type(atstype_ptrk) env0, atstyvar_type(a) env1, atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret15) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1351(line=68, offs=10) -- 1382(line=68, offs=41)
*/
ATSINSflab(__patsflab___patsfun_5):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 1363(line=68, offs=22) -- 1382(line=68, offs=41)
*/
ATSINSmove_void(tmpret15, server_4(env1, arg0, env0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret15) ;
} /* end of [__patsfun_5] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2184(line=86, offs=19) -- 2207(line=86, offs=42)
*/
/*
local: 
global: nil$6$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstype_boxed) ;
ATStmpdec(tmp17, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2176(line=86, offs=11) -- 2207(line=86, offs=42)
*/
ATSINSflab(__patsflab_nil):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2194(line=86, offs=29) -- 2206(line=86, offs=41)
*/
ATSINSmove(tmp17, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2189(line=86, offs=24) -- 2207(line=86, offs=42)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmpret16, postiats_tyrec_0) ;
ATSINSstore_boxrec_ofs(tmpret16, postiats_tyrec_0, atslab__0, ATSPMVi0nt(0)) ;
ATSINSstore_boxrec_ofs(tmpret16, postiats_tyrec_0, atslab__1, tmp17) ;
ATSINSmove_boxrec_end()
ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2231(line=88, offs=23) -- 2365(line=95, offs=4)
*/
/*
local: 
global: enq$7$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(atstype_boxed arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstype_boxed) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp21) ;
ATStmpdec(tmp22, atstype_boxed) ;
// ATStmpdec_void(tmp23) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2219(line=88, offs=11) -- 2365(line=95, offs=4)
*/
ATSINSflab(__patsflab_enq):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2244(line=88, offs=36) -- 2365(line=95, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2256(line=89, offs=8) -- 2257(line=89, offs=9)
*/
ATSINSmove(tmp19, ATSSELboxrec(arg0, postiats_tyrec_0, atslab__0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2259(line=89, offs=11) -- 2261(line=89, offs=13)
*/
ATSINSmove(tmp20, ATSSELboxrec(arg0, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2316(line=91, offs=22) -- 2323(line=91, offs=29)
*/

ATSINSmove_con0(tmp22, 0) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2304(line=91, offs=10) -- 2324(line=91, offs=30)
*/
ATSINSmove_void(tmp21, libsession__choose(ATSPMVrefarg0(tmp20), tmp22)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2334(line=92, offs=10) -- 2346(line=92, offs=22)
*/
ATSINSmove_void(tmp23, libsession__send(ATSPMVrefarg0(tmp20), arg1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2354(line=94, offs=4) -- 2357(line=94, offs=7)
*/
ATSINSmove(tmp24, ats2erlpre_add_int1_int1(tmp19, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2352(line=94, offs=2) -- 2361(line=94, offs=11)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmpret18, postiats_tyrec_0) ;
ATSINSstore_boxrec_ofs(tmpret18, postiats_tyrec_0, atslab__0, tmp24) ;
ATSINSstore_boxrec_ofs(tmpret18, postiats_tyrec_0, atslab__1, tmp20) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2244(line=88, offs=36) -- 2365(line=95, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2389(line=97, offs=23) -- 2542(line=105, offs=4)
*/
/*
local: 
global: deq$8$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstype_boxed) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp27, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp28) ;
ATStmpdec(tmp29, atstype_boxed) ;
ATStmpdec(tmp30, atstyvar_type(a)) ;
ATStmpdec(tmp31, atstype_boxed) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2377(line=97, offs=11) -- 2542(line=105, offs=4)
*/
ATSINSflab(__patsflab_deq):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2399(line=97, offs=33) -- 2542(line=105, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2411(line=98, offs=8) -- 2412(line=98, offs=9)
*/
ATSINSmove(tmp26, ATSSELboxrec(arg0, postiats_tyrec_0, atslab__0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2414(line=98, offs=11) -- 2416(line=98, offs=13)
*/
ATSINSmove(tmp27, ATSSELboxrec(arg0, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2472(line=100, offs=22) -- 2479(line=100, offs=29)
*/

ATSINSmove_con0(tmp29, 1) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2460(line=100, offs=10) -- 2480(line=100, offs=30)
*/
ATSINSmove_void(tmp28, libsession__choose(ATSPMVrefarg0(tmp27), tmp29)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2509(line=102, offs=10) -- 2516(line=102, offs=17)
*/
ATSINSmove(tmp30, libsession__recv(ATSPMVrefarg0(tmp27))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2530(line=104, offs=9) -- 2533(line=104, offs=12)
*/
ATSINSmove(tmp32, ats2erlpre_sub_int1_int1(tmp26, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2528(line=104, offs=7) -- 2537(line=104, offs=16)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp31, postiats_tyrec_0) ;
ATSINSstore_boxrec_ofs(tmp31, postiats_tyrec_0, atslab__0, tmp32) ;
ATSINSstore_boxrec_ofs(tmp31, postiats_tyrec_0, atslab__1, tmp27) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2523(line=104, offs=2) -- 2538(line=104, offs=17)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmpret25, postiats_tyrec_1) ;
ATSINSstore_boxrec_ofs(tmpret25, postiats_tyrec_1, atslab__0, tmp30) ;
ATSINSstore_boxrec_ofs(tmpret25, postiats_tyrec_1, atslab__1, tmp31) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2399(line=97, offs=33) -- 2542(line=105, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret25) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2563(line=107, offs=20) -- 2692(line=114, offs=4)
*/
/*
local: 
global: free$9$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret33) ;
ATStmpdec(tmp34, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp35) ;
ATStmpdec(tmp36, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2554(line=107, offs=11) -- 2692(line=114, offs=4)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2573(line=107, offs=30) -- 2692(line=114, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2588(line=108, offs=11) -- 2590(line=108, offs=13)
*/
ATSINSmove(tmp34, ATSSELboxrec(arg0, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2646(line=110, offs=22) -- 2654(line=110, offs=30)
*/

ATSINSmove_con0(tmp36, 1) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2634(line=110, offs=10) -- 2655(line=110, offs=31)
*/
ATSINSmove_void(tmp35, libsession__choose(ATSPMVrefarg0(tmp34), tmp36)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2681(line=113, offs=2) -- 2688(line=113, offs=9)
*/
ATSINSmove_void(tmpret33, libsession__wait(tmp34)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2573(line=107, offs=30) -- 2692(line=114, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret33) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2716(line=116, offs=23) -- 2733(line=116, offs=40)
*/
/*
local: 
global: len$10$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2704(line=116, offs=11) -- 2733(line=116, offs=40)
*/
ATSINSflab(__patsflab_len):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2726(line=116, offs=33) -- 2733(line=116, offs=40)
*/
ATSINSmove(tmpret37, ATSSELboxrec(arg0, postiats_tyrec_0, atslab__0)) ;
ATSfunbody_end()
ATSreturn(tmpret37) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2812(line=119, offs=24) -- 2998(line=128, offs=6)
*/
/*
local: 
global: printall$11$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret38) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp41) ;
// ATStmpdec_void(tmp42) ;
ATStmpdec(tmp43, atstype_boxed) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp45, atstype_boxed) ;
// ATStmpdec_void(tmp46) ;
// ATStmpdec_void(tmp47) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2799(line=119, offs=11) -- 2998(line=128, offs=6)
*/
ATSINSflab(__patsflab_printall):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2827(line=120, offs=5) -- 2842(line=120, offs=20)
*/
ATSINSmove(tmp40, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2827(line=120, offs=5) -- 2846(line=120, offs=24)
*/
ATSINSmove(tmp39, ats2erlpre_eq_int1_int1(tmp40, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2824(line=120, offs=2) -- 2998(line=128, offs=6)
*/
ATSif(
tmp39
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2854(line=121, offs=8) -- 2868(line=121, offs=22)
*/
ATSINSmove_void(tmp41, ats2erlpre_print_string(ATSPMVstring("nil"))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2854(line=121, offs=8) -- 2868(line=121, offs=22)
*/
ATSINSmove_void(tmp42, ats2erlpre_print_newline()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2870(line=121, offs=24) -- 2886(line=121, offs=40)
*/
ATSINSmove_void(tmpret38, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free(arg0)) ;

} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2897(line=123, offs=3) -- 2998(line=128, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2923(line=124, offs=22) -- 2944(line=124, offs=43)
*/
ATSINSmove(tmp43, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq(arg0)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2911(line=124, offs=10) -- 2912(line=124, offs=11)
*/
ATSINSmove(tmp44, ATSSELboxrec(tmp43, postiats_tyrec_2, atslab__0)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2914(line=124, offs=13) -- 2919(line=124, offs=18)
*/
ATSINSmove(tmp45, ATSSELboxrec(tmp43, postiats_tyrec_2, atslab__1)) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2957(line=125, offs=12) -- 2967(line=125, offs=22)
*/
ATSINSmove_void(tmp46, ats2erlpre_print_int(tmp44)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2957(line=125, offs=12) -- 2967(line=125, offs=22)
*/
ATSINSmove_void(tmp47, ats2erlpre_print_newline()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2977(line=127, offs=4) -- 2991(line=127, offs=18)
*/
ATSINSmove_void(tmpret38, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(tmp45)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 2897(line=123, offs=3) -- 2998(line=128, offs=6)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret38) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3040(line=131, offs=16) -- 3452(line=148, offs=2)
*/
/*
local: 
global: test$12$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret48) ;
ATStmpdec(tmp49, atstype_boxed) ;
ATStmpdec(tmp50, atstype_boxed) ;
ATStmpdec(tmp51, atstype_boxed) ;
ATStmpdec(tmp52, atstype_boxed) ;
ATStmpdec(tmp53, atstype_boxed) ;
ATStmpdec(tmp54, atstype_boxed) ;
ATStmpdec(tmp55, atstype_boxed) ;
ATStmpdec(tmp56, atstype_boxed) ;
ATStmpdec(tmp57, atstype_boxed) ;
ATStmpdec(tmp58, atstype_boxed) ;
ATStmpdec(tmp59, atstype_boxed) ;
// ATStmpdec_void(tmp60) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3035(line=131, offs=11) -- 3452(line=148, offs=2)
*/
ATSINSflab(__patsflab_test):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3045(line=131, offs=21) -- 3452(line=148, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3070(line=133, offs=14) -- 3082(line=133, offs=26)
*/
ATSINSmove(tmp49, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3097(line=135, offs=14) -- 3117(line=135, offs=34)
*/
ATSINSmove(tmp50, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp49, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3131(line=136, offs=14) -- 3151(line=136, offs=34)
*/
ATSINSmove(tmp51, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp50, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3165(line=137, offs=14) -- 3185(line=137, offs=34)
*/
ATSINSmove(tmp52, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp51, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3199(line=138, offs=14) -- 3219(line=138, offs=34)
*/
ATSINSmove(tmp53, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp52, ATSPMVi0nt(4))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3233(line=139, offs=14) -- 3253(line=139, offs=34)
*/
ATSINSmove(tmp54, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp53, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3267(line=140, offs=14) -- 3287(line=140, offs=34)
*/
ATSINSmove(tmp55, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp54, ATSPMVi0nt(6))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3301(line=141, offs=14) -- 3321(line=141, offs=34)
*/
ATSINSmove(tmp56, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp55, ATSPMVi0nt(7))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3335(line=142, offs=14) -- 3355(line=142, offs=34)
*/
ATSINSmove(tmp57, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp56, ATSPMVi0nt(8))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3369(line=143, offs=14) -- 3389(line=143, offs=34)
*/
ATSINSmove(tmp58, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp57, ATSPMVi0nt(9))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3403(line=144, offs=14) -- 3424(line=144, offs=35)
*/
ATSINSmove(tmp59, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(tmp58, ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3435(line=146, offs=10) -- 3449(line=146, offs=24)
*/
ATSINSmove_void(tmp60, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(tmp59)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3045(line=131, offs=21) -- 3047(line=131, offs=23)
*/
ATSINSmove_void(tmpret48, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/queue.dats: 3045(line=131, offs=21) -- 3452(line=148, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret48) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/output/teststub.dats: 406(line=19, offs=19) -- 418(line=19, offs=31)
*/
/*
local: 
global: r$13$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
r()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret61) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/teststub.dats: 398(line=19, offs=11) -- 418(line=19, offs=31)
*/
ATSINSflab(__patsflab_runtest):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/output/teststub.dats: 411(line=19, offs=24) -- 418(line=19, offs=31)
*/
ATSINSmove_void(tmpret61, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test()) ;

ATSfunbody_end()
ATSreturn_void(tmpret61) ;
} /* end of [r] */

#if(0)
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
#endif // end of [#if(0)]

/* ****** ****** */

/* end-of-compilation-unit */
