%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2017-4-20: 17h: 3m
%%
%%%%%%

%%
%% ATSextcode_beg()
%%
-module(test).
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(export_all).
-compile(debug_info).
-include("$PATSHOME/contrib/libatscc2erl/ATS2-0.3.2/output/libatscc2erl_all.hrl").
-include("./session.hrl").
%%
%% ATSextcode_end()
%%

%%fun%%
f__patsfun_2__closurerize() -> 
%{
  {fun({_}, XArg0) -> f__patsfun_2(XArg0) end}.
%}


%%fun%%
f__patsfun_5__closurerize(XEnv0, XEnv1) -> 
%{
  {fun({_, Cenv1, Cenv2}, XArg0) -> f__patsfun_5(Cenv1, Cenv2, XArg0) end, XEnv0, XEnv1}.
%}


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty() ->
%{
%%
%% knd = 0
%% var Tmpret0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_empty,
  libsession__create(f__patsfun_2__closurerize()).
%} // end-of-function


%%fun%%
server_1(Arg0) ->
%{
%%
%% knd = 0
%% var Tmp2
%% var Tmp3
%% var Tmp4
%% var Tmp5
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_server_1,
  Tmp2 = libsession__offer(Arg0),
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(not(?ATSCKpat_con0(Tmp2, 1))) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      libsession__close(Arg0);
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp3 = libsession__recv(Arg0),
      Tmp4 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty(),
      Tmp5 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem(Tmp4, Tmp3),
      libsession__cut(Tmp5, Arg0);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f__patsfun_2(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_2,
  server_1(Arg0).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__elem(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret7
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_elem,
  libsession__create(f__patsfun_5__closurerize(Arg0, Arg1)).
%} // end-of-function


%%fun%%
server_4(Env0, Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmp9
%% var Tmp11
%% var Tmp13
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_server_4,
  Tmp9 = libsession__offer(Arg0),
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(not(?ATSCKpat_con0(Tmp9, 1))) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      libsession__send(Arg0, Env0),
      libsession__cut(Arg0, Arg1);
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp11 = libsession__recv(Arg0),
      Tmp13 = 0,
      libsession__choose(Arg1, Tmp13),
      libsession__send(Arg1, Tmp11),
      server_4(Env0, Arg0, Arg1);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f__patsfun_5(Env0, Env1, Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_5,
  server_4(Env1, Arg0, Env0).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil() ->
%{
%%
%% knd = 0
%% var Tmpret16
%% var Tmp17
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_nil,
  Tmp17 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__empty(),
  {0, Tmp17}.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret18
%% var Tmp19
%% var Tmp20
%% var Tmp22
%% var Tmp24
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_enq,
  Tmp19 = ?ATSSELboxrec(Arg0, 0),
  Tmp20 = ?ATSSELboxrec(Arg0, 1),
  Tmp22 = 0,
  libsession__choose(Tmp20, Tmp22),
  libsession__send(Tmp20, Arg1),
  Tmp24 = ats2erlpre_add_int1_int1(Tmp19, 1),
  {Tmp24, Tmp20}.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret25
%% var Tmp26
%% var Tmp27
%% var Tmp29
%% var Tmp30
%% var Tmp31
%% var Tmp32
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_deq,
  Tmp26 = ?ATSSELboxrec(Arg0, 0),
  Tmp27 = ?ATSSELboxrec(Arg0, 1),
  Tmp29 = 1,
  libsession__choose(Tmp27, Tmp29),
  Tmp30 = libsession__recv(Tmp27),
  Tmp32 = ats2erlpre_sub_int1_int1(Tmp26, 1),
  Tmp31 = {Tmp32, Tmp27},
  {Tmp30, Tmp31}.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free(Arg0) ->
%{
%%
%% knd = 0
%% var Tmp34
%% var Tmp36
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_free,
  Tmp34 = ?ATSSELboxrec(Arg0, 1),
  Tmp36 = 1,
  libsession__choose(Tmp34, Tmp36),
  libsession__wait(Tmp34).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret37
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_len,
  ?ATSSELboxrec(Arg0, 0).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(Arg0) ->
%{
%%
%% knd = 0
%% var Tmp39
%% var Tmp40
%% var Tmp43
%% var Tmp44
%% var Tmp45
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_printall,
  Tmp40 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__len(Arg0),
  Tmp39 = ats2erlpre_eq_int1_int1(Tmp40, 0),
  if
    Tmp39 ->
      ats2erlpre_print_string("nil"),
      ats2erlpre_print_newline(),
      f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__free(Arg0);
    %% if-then
    true ->
      Tmp43 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__deq(Arg0),
      Tmp44 = ?ATSSELboxrec(Tmp43, 0),
      Tmp45 = ?ATSSELboxrec(Tmp43, 1),
      ats2erlpre_print_int(Tmp44),
      ats2erlpre_print_newline(),
      f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(Tmp45)
    %% if-else
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test() ->
%{
%%
%% knd = 0
%% var Tmp49
%% var Tmp50
%% var Tmp51
%% var Tmp52
%% var Tmp53
%% var Tmp54
%% var Tmp55
%% var Tmp56
%% var Tmp57
%% var Tmp58
%% var Tmp59
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_test,
  Tmp49 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__nil(),
  Tmp50 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp49, 1),
  Tmp51 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp50, 2),
  Tmp52 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp51, 3),
  Tmp53 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp52, 4),
  Tmp54 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp53, 5),
  Tmp55 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp54, 6),
  Tmp56 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp55, 7),
  Tmp57 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp56, 8),
  Tmp58 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp57, 9),
  Tmp59 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__enq(Tmp58, 10),
  f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__printall(Tmp59),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
r() ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_runtest,
  f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_output_057_teststub_056_dats__test().
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2017-4-20: 17h: 3m
%%
%%%%%%

%%fun%%
f__patsfun_1__closurerize(XEnv0, XEnv1) -> 
%{
  {fun({_, Cenv1, Cenv2}) -> f__patsfun_1(Cenv1, Cenv2) end, XEnv0, XEnv1}.
%}


%%fun%%
libsession__create(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret0
%% var Tmp1
%% var Tmp2
%% var Tmp3
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_create,
  Tmp1 = libsession__create(),
  Tmp2 = ?ATSSELboxrec(Tmp1, 0),
  Tmp3 = ?ATSSELboxrec(Tmp1, 1),
  libsession__spawn_link(f__patsfun_1__closurerize(Arg0, Tmp2)),
  Tmp3.
%} // end-of-function


%%fun%%
f__patsfun_1(Env0, Env1) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_1,
  ?ATSfunclo_clo(Env0)(Env0, Env1),
  ?ATSINSmove_void().
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
