%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2016-3-6:  0h:33m
%%
%%%%%%

%%
%% ATSextcode_beg()
%%
%%
%%-module(libsession).
%%
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(export_all).
-compile(debug_info).
%%
-include("$PATSHOMERELOC/contrib/libatscc/libatscc2erl/libatscc2erl_all.hrl").
-include("./session.hrl").
%%
%%
%% ATSextcode_end()
%%

%% ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set)

%% ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__name)

%% ATSassume(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__session)

%%fun%%
f__patsfun_14__closurerize() -> 
%{
  {fun({_}, XArg0, XArg1, XArg2) -> f__patsfun_14(XArg0, XArg1, XArg2) end}.
%}


%%fun%%
f__patsfun_18__closurerize(XEnv0, XEnv1, XEnv2, XEnv3, XEnv4) -> 
%{
  {fun({_, Cenv1, Cenv2, Cenv3, Cenv4, Cenv5}) -> f__patsfun_18(Cenv1, Cenv2, Cenv3, Cenv4, Cenv5) end, XEnv0, XEnv1, XEnv2, XEnv3, XEnv4}.
%}


%%fun%%
f__patsfun_19__closurerize(XEnv0) -> 
%{
  {fun({_, Cenv1}, XArg0) -> f__patsfun_19(Cenv1, XArg0) end, XEnv0}.
%}


%%fun%%
f__patsfun_21__closurerize(XEnv0, XEnv1, XEnv2, XEnv3, XEnv4) -> 
%{
  {fun({_, Cenv1, Cenv2, Cenv3, Cenv4, Cenv5}) -> f__patsfun_21(Cenv1, Cenv2, Cenv3, Cenv4, Cenv5) end, XEnv0, XEnv1, XEnv2, XEnv3, XEnv4}.
%}


%%fun%%
f__patsfun_22__closurerize(XEnv0) -> 
%{
  {fun({_, Cenv1}, XArg0) -> f__patsfun_22(Cenv1, XArg0) end, XEnv0}.
%}


%%fun%%
f__patsfun_23__closurerize(XEnv0) -> 
%{
  {fun({_, Cenv1}, XArg0) -> f__patsfun_23(Cenv1, XArg0) end, XEnv0}.
%}


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__empty_set() ->
%{
%%
%% knd = 0
%% var Tmpret0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_empty_set,
  atscc2erl_null.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_add(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret1
%% var Tmp2
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_add,
  Tmp2 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_member(Arg1, Arg0),
  if
    Tmp2 ->
      Arg0;
    %% if-then
    true ->
      {Arg1, Arg0}
    %% if-else
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_del(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret3
%% var Tmp4
%% var Tmp5
%% var Tmp6
%% var Tmp7
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_del,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      Arg0;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp4 = ?ATSSELcon(Arg0, 0),
      Tmp5 = ?ATSSELcon(Arg0, 1),
      Tmp6 = ats2erlpre_eq_int1_int1(Arg1, Tmp4),
      if
        Tmp6 ->
          Tmp5;
        %% if-then
        true ->
          Tmp7 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_del(Tmp5, Arg1),
          {Tmp4, Tmp7}
        %% if-else
      end;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_union(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret8
%% var Tmp9
%% var Tmp10
%% var Tmp11
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_union,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      Arg1;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp9 = ?ATSSELcon(Arg0, 0),
      Tmp10 = ?ATSSELcon(Arg0, 1),
      Tmp11 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_add(Arg1, Tmp9),
      f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_union(Tmp10, Tmp11);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_intersect(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret12
%% var Tmp13
%% var Tmp14
%% var Tmp15
%% var Tmp16
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_intersect,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      atscc2erl_null;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp13 = ?ATSSELcon(Arg0, 0),
      Tmp14 = ?ATSSELcon(Arg0, 1),
      Tmp15 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_member(Tmp13, Arg1),
      if
        Tmp15 ->
          Tmp16 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_intersect(Tmp14, Arg1),
          {Tmp13, Tmp16};
        %% if-then
        true ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_intersect(Tmp14, Arg1)
        %% if-else
      end;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret17
%% var Tmp18
%% var Tmp19
%% var Tmp20
%% var Tmp21
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_difference,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      atscc2erl_null;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp18 = ?ATSSELcon(Arg0, 0),
      Tmp19 = ?ATSSELcon(Arg0, 1),
      Tmp20 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_member(Tmp18, Arg1),
      if
        Tmp20 ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Tmp19, Arg1);
        %% if-then
        true ->
          Tmp21 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Tmp19, Arg1),
          {Tmp18, Tmp21}
        %% if-else
      end;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_member(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret22
%% var Tmp23
%% var Tmp24
%% var Tmp25
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_member,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg1)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      false;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp23 = ?ATSSELcon(Arg1, 0),
      Tmp24 = ?ATSSELcon(Arg1, 1),
      Tmp25 = ats2erlpre_eq_int1_int1(Tmp23, Arg0),
      if
        Tmp25 ->
          true;
        %% if-then
        true ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_member(Arg0, Tmp24)
        %% if-else
      end;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_subset(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret26
%% var Tmp27
%% var Tmp28
%% var Tmp29
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_subset,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      true;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp27 = ?ATSSELcon(Arg0, 0),
      Tmp28 = ?ATSSELcon(Arg0, 1),
      Tmp29 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_member(Tmp27, Arg1),
      if
        Tmp29 ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_subset(Tmp28, Arg1);
        %% if-then
        true ->
          false
        %% if-else
      end;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_eq(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret30
%% var Tmp31
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_eq,
  Tmp31 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_subset(Arg0, Arg1),
  if
    Tmp31 ->
      f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_subset(Arg1, Arg0);
    %% if-then
    true ->
      false
    %% if-else
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_neq(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret32
%% var Tmp33
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_neq,
  Tmp33 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_eq(Arg0, Arg1),
  ats2erlpre_neg_bool1(Tmp33).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_is_empty(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret34
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_is_empty,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      true;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      false;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_range(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret35
%% var Tmp36
%% var Tmp37
%% var Tmp38
%% var Tmp39
%% var Tmp40
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_range,
  Tmp36 = ats2erlpre_eq_int1_int1(Arg0, Arg1),
  if
    Tmp36 ->
      Tmp37 = atscc2erl_null,
      {Arg0, Tmp37};
    %% if-then
    true ->
      Tmp38 = ats2erlpre_gt_int1_int1(Arg0, Arg1),
      if
        Tmp38 ->
          Tmp40 = ats2erlpre_sub_int1_int1(Arg0, 1),
          Tmp39 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_range(Tmp40, Arg1),
          {Arg0, Tmp39};
        %% if-then
        true ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_range(Arg1, Arg0)
        %% if-else
      end
    %% if-else
  end.
%} // end-of-function


%%fun%%
set2erl_12(Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret41
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set2erl_12,
  libsession__set2erl(Arg0, f__patsfun_14__closurerize()).
%} // end-of-function


%%fun%%
set_reduce_13(Arg0, Arg1, Arg2) ->
%{
%%
%% knd = 0
%% var Tmpret42
%% var Tmp43
%% var Tmp44
%% var Tmp45
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_set_reduce_13,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      Arg1;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp43 = ?ATSSELcon(Arg0, 0),
      Tmp44 = ?ATSSELcon(Arg0, 1),
      Tmp45 = set_reduce_13(Tmp44, Arg1, Arg2),
      ?ATSfunclo_clo(Arg2)(Arg2, Tmp43, Tmp45);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f__patsfun_14(Arg0, Arg1, Arg2) ->
%{
%%
%% knd = 0
%% var Tmpret46
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_14,
  set_reduce_13(Arg0, Arg1, Arg2).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__make_name(Arg0, Arg1, Arg2) ->
%{
%%
%% knd = 0
%% var Tmpret47
%% var Tmp48
%% var Tmp49
%% var Tmp50
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_make_name,
  Tmp49 = {2, Arg0},
  Tmp48 = {6, Tmp49, Arg1},
  Tmp50 = ats2erlpre_string2atom(Arg2),
  {Arg0, Tmp48, Tmp50}.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret51
%% var Tmp52
%% var Tmp53
%% var Tmp54
%% var Tmp55
%% var Tmp56
%% var Tmp57
%% var Tmp58
%% var Tmp59
%% var Tmp60
%% var Tmp61
%% var Tmp62
%% var Tmp63
%% var Tmp64
%% var Tmp65
%% var Tmp66
%% var Tmp67
%% var Tmp68
%% var Tmp69
%% var Tmp70
%% var Tmp71
%% var Tmp72
%% var Tmp73
%% var Tmp74
%% var Tmp75
%% var Tmp76
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_is_equal,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(not(?ATSCKpat_con0(Arg0, 0))) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      if(not(?ATSCKpat_con0(Arg1, 0))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 3)
      end;
      3 ->
      true;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      4 ->
      if(not(?ATSCKpat_con0(Arg0, 1))) -> Casefun(Casefun, 7); true ->
        Casefun(Casefun, 5)
      end;
      5 ->
      if(not(?ATSCKpat_con0(Arg1, 1))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 6)
      end;
      6 ->
      true;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      7 ->
      if(not(?ATSCKpat_con1(Arg0, 3))) -> Casefun(Casefun, 10); true ->
        Casefun(Casefun, 8)
      end;
      8 ->
      if(not(?ATSCKpat_con1(Arg1, 3))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 9)
      end;
      9 ->
      Tmp52 = ?ATSSELcon(Arg0, 1),
      Tmp53 = ?ATSSELcon(Arg0, 2),
      Tmp54 = ?ATSSELcon(Arg1, 1),
      Tmp55 = ?ATSSELcon(Arg1, 2),
      Tmp72 = ats2erlpre_eq_int1_int1(Tmp52, Tmp54),
      if
        Tmp72 ->
          ats2erlpre_eq_int1_int1(Tmp53, Tmp55);
        %% if-then
        true ->
          false
        %% if-else
      end;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      10 ->
      if(not(?ATSCKpat_con1(Arg0, 4))) -> Casefun(Casefun, 13); true ->
        Casefun(Casefun, 11)
      end;
      11 ->
      if(not(?ATSCKpat_con1(Arg1, 4))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 12)
      end;
      12 ->
      Tmp56 = ?ATSSELcon(Arg0, 1),
      Tmp57 = ?ATSSELcon(Arg0, 2),
      Tmp58 = ?ATSSELcon(Arg1, 1),
      Tmp59 = ?ATSSELcon(Arg1, 2),
      Tmp73 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_eq(Tmp56, Tmp58),
      if
        Tmp73 ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_eq(Tmp57, Tmp59);
        %% if-then
        true ->
          false
        %% if-else
      end;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      13 ->
      if(not(?ATSCKpat_con1(Arg0, 5))) -> Casefun(Casefun, 16); true ->
        Casefun(Casefun, 14)
      end;
      14 ->
      if(not(?ATSCKpat_con1(Arg1, 5))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 15)
      end;
      15 ->
      Tmp60 = ?ATSSELcon(Arg0, 1),
      Tmp61 = ?ATSSELcon(Arg0, 2),
      Tmp62 = ?ATSSELcon(Arg0, 3),
      Tmp63 = ?ATSSELcon(Arg1, 1),
      Tmp64 = ?ATSSELcon(Arg1, 2),
      Tmp65 = ?ATSSELcon(Arg1, 3),
      Tmp75 = ats2erlpre_eq_int1_int1(Tmp60, Tmp63),
      if
        Tmp75 ->
          Tmp74 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Tmp61, Tmp64);
        %% if-then
        true ->
          Tmp74 = false
        %% if-else
      end,
      if
        Tmp74 ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Tmp62, Tmp65);
        %% if-then
        true ->
          false
        %% if-else
      end;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      16 ->
      if(not(?ATSCKpat_con1(Arg0, 6))) -> Casefun(Casefun, 19); true ->
        Casefun(Casefun, 17)
      end;
      17 ->
      if(not(?ATSCKpat_con1(Arg1, 6))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 18)
      end;
      18 ->
      Tmp66 = ?ATSSELcon(Arg0, 1),
      Tmp67 = ?ATSSELcon(Arg0, 2),
      Tmp68 = ?ATSSELcon(Arg1, 1),
      Tmp69 = ?ATSSELcon(Arg1, 2),
      Tmp76 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Tmp66, Tmp68),
      if
        Tmp76 ->
          f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Tmp67, Tmp69);
        %% if-then
        true ->
          false
        %% if-else
      end;
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      19 ->
      if(not(?ATSCKpat_con1(Arg0, 7))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 20)
      end;
      20 ->
      if(not(?ATSCKpat_con1(Arg1, 7))) -> Casefun(Casefun, 22); true ->
        Casefun(Casefun, 21)
      end;
      21 ->
      Tmp70 = ?ATSSELcon(Arg0, 1),
      Tmp71 = ?ATSSELcon(Arg1, 1),
      f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Tmp70, Tmp71);
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      22 ->
      false;
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__init(Arg0, Arg1, Arg2) ->
%{
%%
%% knd = 0
%% var Tmp78
%% var Tmp79
%% var Tmp80
%% var Tmp81
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_init,
  Tmp78 = ?ATSSELboxrec(Arg0, 0),
  Tmp79 = ?ATSSELboxrec(Arg0, 1),
  Tmp80 = ?ATSSELboxrec(Arg0, 2),
  Tmp81 = libsession_spawn(f__patsfun_18__closurerize(Arg1, Arg2, Tmp78, Tmp79, Tmp80)),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f__patsfun_18(Env0, Env1, Env2, Env3, Env4) ->
%{
%%
%% knd = 0
%% var Tmp83
%% var Tmp84
%% var Tmp85
%% var Tmp87
%% var Tmp88
%% var Tmp89
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_18,
  Tmp84 = set2erl_12(Env0),
  Tmp85 = set2erl_12(Env2),
  Tmp83 = libsession__init(Env4, Tmp84, Tmp85, Env3, f__patsfun_19__closurerize(Env3)),
  Tmp88 = is_pid(Tmp83),
  if
    Tmp88 ->
      Tmp89 = {Tmp83, Env0, Env2},
      Tmp87 = {Tmp89};
    %% if-then
    true ->
      Tmp87 = atscc2erl_null
    %% if-else
  end,
  ?ATSfunclo_clo(Env1)(Env1, Tmp87),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f__patsfun_19(Env0, Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret86
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_19,
  f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Arg0, Env0).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__create(Arg0, Arg1, Arg2) ->
%{
%%
%% knd = 0
%% var Tmpret91
%% var Tmp92
%% var Tmp93
%% var Tmp94
%% var Tmp95
%% var Tmp96
%% var Tmp106
%% var Tmp108
%% var Tmp109
%% var Tmp110
%% var Tmp111
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_create,
  Tmp92 = libsession_make_ref(),
  Tmp93 = ?ATSSELcon(Arg1, 1),
  Tmp94 = ?ATSSELcon(Tmp93, 1),
  Tmp95 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Tmp94, Arg0),
  Tmp96 = libsession_spawn(f__patsfun_21__closurerize(Arg1, Arg2, Tmp92, Tmp94, Tmp95)),
  Tmp108 = set2erl_12(Arg0),
  Tmp109 = set2erl_12(Tmp94),
  Tmp106 = libsession__init(Tmp92, Arg1, f__patsfun_23__closurerize(Arg1), Tmp108, Tmp109),
  Tmp110 = is_pid(Tmp106),
  if
    Tmp110 ->
      Tmp111 = {Tmp106, Arg0, Tmp94},
      {Tmp111};
    %% if-then
    true ->
      atscc2erl_null
    %% if-else
  end.
%} // end-of-function


%%fun%%
f__patsfun_21(Env0, Env1, Env2, Env3, Env4) ->
%{
%%
%% knd = 0
%% var Tmp98
%% var Tmp100
%% var Tmp101
%% var Tmp102
%% var Tmp103
%% var Tmp104
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_21,
  Tmp100 = set2erl_12(Env4),
  Tmp101 = set2erl_12(Env3),
  Tmp98 = libsession__init(Env2, Env0, f__patsfun_22__closurerize(Env0), Tmp100, Tmp101),
  Tmp103 = is_pid(Tmp98),
  if
    Tmp103 ->
      Tmp104 = {Tmp98, Env4, Env3},
      Tmp102 = {Tmp104};
    %% if-then
    true ->
      Tmp102 = atscc2erl_null
    %% if-else
  end,
  ?ATSfunclo_clo(Env1)(Env1, Tmp102),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f__patsfun_22(Env0, Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret99
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_22,
  f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Arg0, Env0).
%} // end-of-function


%%fun%%
f__patsfun_23(Env0, Arg0) ->
%{
%%
%% knd = 0
%% var Tmpret107
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_23,
  f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__is_equal(Arg0, Env0).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__send(Arg0, Arg1, Arg2, Arg3) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_send,
  libsession__send(?ATSSELcon(Arg0, 0), Arg1, Arg2, Arg3),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__receive(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret114
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_receive,
  libsession__recv(?ATSSELcon(Arg0, 0), Arg1).
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__skip_msg(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_skip_msg,
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__skip_mmsg(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_skip_mmsg,
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__proj_mmsg(Arg0) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_proj_mmsg,
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__close(Arg0) ->
%{
%%
%% knd = 0
%% var Tmp119
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_close,
  Tmp119 = ?ATSSELcon(Arg0, 0),
  %% ATSINSfreecon(Arg0);,
  libsession__close(Tmp119),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__link(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret121
%% var Tmp122
%% var Tmp123
%% var Tmp124
%% var Tmp125
%% var Tmp126
%% var Tmp127
%% var Tmp128
%% var Tmp129
%% var Tmp130
%% var Tmp131
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_link,
  Tmp122 = ?ATSSELcon(Arg0, 0),
  Tmp123 = ?ATSSELcon(Arg0, 1),
  %% ATSINSfreecon(Arg0);,
  Tmp124 = ?ATSSELcon(Arg1, 0),
  Tmp125 = ?ATSSELcon(Arg1, 1),
  Tmp126 = ?ATSSELcon(Arg1, 2),
  %% ATSINSfreecon(Arg1);,
  Tmp129 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Tmp126, Tmp123),
  Tmp130 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Tmp126, Tmp125),
  Tmp128 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_union(Tmp129, Tmp130),
  Tmp127 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_difference(Tmp126, Tmp128),
  Tmp131 = libsession__link(Tmp122, Tmp124),
  {Tmp131, Tmp127, Tmp126}.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__offer(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmpret132
%% var Tmp133
%% var Tmp134
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_offer,
  Tmp133 = libsession__offer(?ATSSELcon(Arg0, 0), Arg1),
  Tmp134 = ats2erlpre_eq_int0_int0(Tmp133, 0),
  if
    Tmp134 ->
      0;
    %% if-then
    true ->
      1
    %% if-else
  end.
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__choose_fst(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_choose_fst,
  libsession__choose(?ATSSELcon(Arg0, 0), 0),
  ?ATSINSmove_void().
%} // end-of-function


%%fun%%
f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__choose_snd(Arg0, Arg1) ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_choose_snd,
  libsession__choose(?ATSSELcon(Arg0, 0), 1),
  ?ATSINSmove_void().
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
