%%%%%%
%%
%% The Erlang code is generated by atscc2erl
%% The starting compilation time is: 2016-3-6: 12h:24m
%%
%%%%%%

%%
%% ATSextcode_beg()
%%
%%
-module(test).
%%
-compile(nowarn_unused_vars).
-compile(nowarn_unused_function).
-compile(export_all).
-compile(debug_info).
%%
%%-include("$PATSHOMERELOC/contrib/libatscc/libatscc2erl/libatscc2erl_all.hrl").
-include("./session.erl").
%%
%%
%% ATSextcode_end()
%%

%%fun%%
f__patsfun_1__closurerize() -> 
%{
  {fun({_}, XArg0) -> f__patsfun_1(XArg0) end}.
%}


%%fun%%
a() ->
%{
%%
%% knd = 0
%% var Tmp1
%% var Tmp2
%% var Tmp3
%% var Tmp4
%% var Tmp5
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_a,
  Tmp2 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_range(0, 2),
  Tmp3 = 0,
  Tmp1 = f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__make_name(Tmp2, Tmp3, "test"),
  Tmp5 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__empty_set(),
  Tmp4 = f_057_Users_057_hwwu_057_Git_057_ats_055_utils_057_intset_056_sats__set_add(Tmp5, 0),
  f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__init(Tmp1, Tmp4, f__patsfun_1__closurerize()).
%} // end-of-function


%%fun%%
f__patsfun_1(Arg0) ->
%{
%%
%% knd = 0
%% var Tmp7
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab___patsfun_1,
  begin
  Casefunx1 =
  fun (Casefun, Tmplab) ->
    %switch(Tmplab) {
    case Tmplab of
      %% ATSbranchseq_beg
      1 ->
      if(?ATSCKptriscons(Arg0)) -> Casefun(Casefun, 4); true ->
        Casefun(Casefun, 2)
      end;
      2 ->
      ats2erlpre_print_string("nothing"),
      ats2erlpre_print_newline();
      %% ATSbranchseq_end
      %% ATSbranchseq_beg
      3 ->
      Casefun(Casefun, 4);
      4 ->
      Tmp7 = ?ATSSELcon(Arg0, 0),
      %% ATSINSfreecon(Arg0);,
      ats2erlpre_print_string("just"),
      ats2erlpre_print_newline(),
      f_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_multiparty_057_session_056_sats__close(Tmp7);
      %% ATSbranchseq_end
      _ -> atscc2erl_caseof_deadcode(?FILE, ?LINE)
    end %% endcase
    %} // end-of-switch
  end, %% endfun
  Casefunx1(Casefunx1, 1)
  end.
%} // end-of-function


%%fun%%
b() ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_b,
  a().
%} // end-of-function


%%fun%%
c() ->
%{
%%
%% knd = 0
%% var Tmplab, Tmplab_erl
%%
  %% __patsflab_c,
  a().
%} // end-of-function

%%%%%%
%%
%% end-of-compilation-unit
%%
%%%%%%
