/*
**
** The C code is generated by [ATS/Postiats-0-3-6]
** The starting compilation time is: 2017-11-28: 15h:33m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(libsession__send)
ATSdyncst_mac(libsession__close)
ATSdyncst_mac(libsession__recv)
ATSdyncst_mac(atspre_assert_errmsg_bool1)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(libsession__wait)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__server(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
loop_1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__client(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
loop_3(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

/*
/Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 506(line=14, offs=26) -- 958(line=30, offs=4)
*/
/*
local: 
global: server$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__server(atstkind_type(atstype_ptrk) arg0, atstkind_type(atstype_ptrk) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
// ATStmpdec_void(tmp1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 491(line=14, offs=11) -- 958(line=30, offs=4)
*/
ATSINSflab(__patsflab_server):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 524(line=14, offs=44) -- 958(line=30, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 561(line=16, offs=12) -- 575(line=16, offs=26)
*/
ATSINSmove_void(tmp1, libsession__send(ATSPMVrefarg0(arg0), arg2)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 923(line=29, offs=2) -- 954(line=29, offs=33)
*/
ATSINSmove_void(tmpret0, loop_1(arg0, arg2, arg1, arg2)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 524(line=14, offs=44) -- 958(line=30, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__server] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 582(line=18, offs=6) -- 917(line=27, offs=37)
*/
/*
local: loop_1$0(level=1)
global: loop_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_type(atstype_ptrk) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy3, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret2) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp4) ;
ATStmpdec(tmp5, atstyvar_type(a)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 582(line=18, offs=6) -- 917(line=27, offs=37)
*/
ATSINSflab(__patsflab_loop_1):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 686(line=19, offs=6) -- 691(line=19, offs=11)
*/
ATSINSmove(tmp3, PMVtmpltcstmat[0](eq_g1int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 683(line=19, offs=3) -- 917(line=27, offs=37)
*/
ATSif(
tmp3
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 762(line=22, offs=8) -- 770(line=22, offs=16)
*/
ATSINSmove_void(tmpret2, libsession__close(arg0)) ;

} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 786(line=24, offs=4) -- 917(line=27, offs=37)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 873(line=26, offs=34) -- 878(line=26, offs=39)
*/
ATSINSmove(tmp6, PMVtmpltcstmat[0](g1int_sub<S2Eextkind(atstype_int)>)(arg3, arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 868(line=26, offs=29) -- 879(line=26, offs=40)
*/
ATSINSmove(tmp5, PMVtmpltcstmat[0](arrayref_get_at_gint<S2Evar(a(4488))><S2Eextkind(atstype_int)>)(arg2, tmp6)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 858(line=26, offs=19) -- 880(line=26, offs=41)
*/
ATSINSmove_void(tmp4, libsession__send(ATSPMVrefarg0(arg0), tmp5)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 898(line=27, offs=18) -- 901(line=27, offs=21)
*/
ATSINSmove(tmp7, PMVtmpltcstmat[0](g1int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 888(line=27, offs=8) -- 913(line=27, offs=33)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, tmp7) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSmove_tlcal(apy3, arg3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_loop_1) ;
ATStailcal_end()

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 786(line=24, offs=4) -- 917(line=27, offs=37)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret2) ;
} /* end of [loop_1] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 981(line=32, offs=22) -- 1613(line=57, offs=4)
*/
/*
local: 
global: client$2$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__client(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstype_boxed) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp10) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp20) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 970(line=32, offs=11) -- 1613(line=57, offs=4)
*/
ATSINSflab(__patsflab_client):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 988(line=32, offs=29) -- 1613(line=57, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1072(line=37, offs=12) -- 1079(line=37, offs=19)
*/
ATSINSmove(tmp9, libsession__recv(ATSPMVrefarg0(arg0))) ;

/* (*nothing*) */
/* (*nothing*) */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1136(line=41, offs=10) -- 1156(line=41, offs=30)
*/
ATSINSmove(tmp11, PMVtmpltcstmat[0](gte_g1int_int<S2Eextkind(atstype_int)>)(tmp9, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1136(line=41, offs=10) -- 1156(line=41, offs=30)
*/
ATSINSmove_void(tmp10, atspre_assert_errmsg_bool1(tmp11, ATSCSTSPmyloc("/Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1136(line=41, offs=10) -- 1156(line=41, offs=30)"))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1188(line=42, offs=32) -- 1196(line=42, offs=40)
*/
ATSINSmove(tmp13, atspre_g1int2uint_int_size(tmp9)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1169(line=42, offs=13) -- 1212(line=42, offs=56)
*/
ATSINSmove(tmp12, PMVtmpltcstmat[0](arrayref_make_elt<S2Evar(a(4502))>)(tmp13, ATSPMVcastfn(cast, atstyvar_type(a), ATSPMVi0nt(0)))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1566(line=54, offs=10) -- 1591(line=54, offs=35)
*/
ATSINSmove_void(tmp20, loop_3(arg0, tmp9, tmp12, tmp9)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1597(line=56, offs=2) -- 1609(line=56, offs=14)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmpret8, postiats_tyrec_0) ;
ATSINSstore_boxrec_ofs(tmpret8, postiats_tyrec_0, atslab__0, tmp9) ;
ATSINSstore_boxrec_ofs(tmpret8, postiats_tyrec_0, atslab__1, tmp12) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 988(line=32, offs=29) -- 1613(line=57, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__client] */

/*
/Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1219(line=44, offs=6) -- 1556(line=53, offs=37)
*/
/*
local: loop_3$0(level=1)
global: loop_3$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_3(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_type(atstype_ptrk) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy3, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret14) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp16) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstyvar_type(a)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1219(line=44, offs=6) -- 1556(line=53, offs=37)
*/
ATSINSflab(__patsflab_loop_3):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1323(line=45, offs=6) -- 1328(line=45, offs=11)
*/
ATSINSmove(tmp15, PMVtmpltcstmat[0](eq_g1int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1320(line=45, offs=3) -- 1556(line=53, offs=37)
*/
ATSif(
tmp15
) ATSthen() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1399(line=48, offs=8) -- 1406(line=48, offs=15)
*/
ATSINSmove_void(tmpret14, libsession__wait(arg0)) ;

} ATSelse() {
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1422(line=50, offs=4) -- 1556(line=53, offs=37)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1500(line=52, offs=25) -- 1505(line=52, offs=30)
*/
ATSINSmove(tmp17, PMVtmpltcstmat[0](g1int_sub<S2Eextkind(atstype_int)>)(arg3, arg1)) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1511(line=52, offs=36) -- 1518(line=52, offs=43)
*/
ATSINSmove(tmp18, libsession__recv(ATSPMVrefarg0(arg0))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1495(line=52, offs=20) -- 1519(line=52, offs=44)
*/
ATSINSmove_void(tmp16, PMVtmpltcstmat[0](arrayref_set_at_gint<S2Evar(a(4502))><S2Eextkind(atstype_int)>)(arg2, tmp17, tmp18)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1537(line=53, offs=18) -- 1540(line=53, offs=21)
*/
ATSINSmove(tmp19, PMVtmpltcstmat[0](g1int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1527(line=53, offs=8) -- 1552(line=53, offs=33)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, tmp19) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSmove_tlcal(apy3, arg3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_loop_3) ;
ATStailcal_end()

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/dependent/tests/dep_array.dats: 1422(line=50, offs=4) -- 1556(line=53, offs=37)
*/
/*
INSletpop()
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret14) ;
} /* end of [loop_3] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_dependent_057_tests_057_dep_array_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
