/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-11-28: 18h: 7m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(testchannel)
ATSdyncst_extfun(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_sats__dualof, (atsrefarg0_type(atstkind_type(atstype_ptrk))), atsvoid_t0ype) ;
ATSdyncst_valdec(ATSLIB_056_prelude_056_unsafe__cast2void, atstype_funptr) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
/Users/hwwu/Git/ats-session-playground/session/session.dats: 283(line=14, offs=1) -- 329(line=18, offs=3)
*/
ATSextcode_beg()
int testchannel () {
	return (void*)0;
}
ATSextcode_end()
#if(0)
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_sats__dualof(atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/Users/hwwu/Git/ats-session-playground/session/session.dats: 167(line=8, offs=26) -- 225(line=11, offs=4)
*/
/*
local: 
global: dualof$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_sats__dualof(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 152(line=8, offs=11) -- 225(line=11, offs=4)
*/
ATSINSflab(__patsflab_dualof):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 218(line=10, offs=1) -- 225(line=11, offs=4)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_sats__dualof] */

/*
/Users/hwwu/Git/ats-session-playground/session/session.dats: 347(line=20, offs=17) -- 580(line=29, offs=2)
*/
/*
local: 
global: mainats_void_0$1$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret1) ;
ATStmpdec(tmp2, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp3) ;
// ATStmpdec_void(tmp4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 341(line=20, offs=11) -- 580(line=29, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 352(line=20, offs=22) -- 580(line=29, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 375(line=22, offs=11) -- 409(line=22, offs=45)
*/
ATSINSmove(tmp2, testchannel()) ;

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 512(line=26, offs=10) -- 528(line=26, offs=26)
*/
ATSINSmove_void(tmp3, _057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_sats__dualof(ATSPMVrefarg0(tmp2))) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 561(line=28, offs=10) -- 577(line=28, offs=26)
*/
ATSINSmove_void(tmp4, ATSfunclo_fun(ATSLIB_056_prelude_056_unsafe__cast2void, (atstkind_type(atstype_ptrk)), atsvoid_t0ype)(tmp2)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 352(line=20, offs=22) -- 354(line=20, offs=24)
*/
ATSINSmove_void(tmpret1, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/hwwu/Git/ats-session-playground/session/session.dats: 352(line=20, offs=22) -- 580(line=29, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret1) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_hwwu_057_Git_057_ats_055_session_055_playground_057_session_057_session_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
